version: "3.9"
services:
  db:
    image: postgres
    container_name: dus-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "9999:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

  app:
#    container_name: dus
    build: .
    environment:
      POSTGRES_DSN: postgresql://postgres:password@dus-database:5432/mydb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: ./server
volumes:
  data: