basePath: /api/v1
definitions:
  github_com_unbeman_av-prac-task_internal_model.CreateSegment:
    properties:
      selection:
        type: number
      slug:
        type: string
    type: object
  github_com_unbeman_av-prac-task_internal_model.OutputError:
    properties:
      message:
        type: string
    type: object
  github_com_unbeman_av-prac-task_internal_model.Segment:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      selection:
        description: 0 < user selection <= 1
        type: number
      slug:
        type: string
      users:
        items:
          $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.User'
        type: array
    type: object
  github_com_unbeman_av-prac-task_internal_model.SegmentInput:
    properties:
      slug:
        type: string
    type: object
  github_com_unbeman_av-prac-task_internal_model.Segments:
    items:
      $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.Segment'
    type: array
  github_com_unbeman_av-prac-task_internal_model.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      name:
        type: string
      segments:
        $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.Segments'
    type: object
  github_com_unbeman_av-prac-task_internal_model.UserInput:
    properties:
      user_id:
        type: integer
    type: object
  github_com_unbeman_av-prac-task_internal_model.UserSegmentsInput:
    properties:
      segments_to_add:
        items:
          type: string
        type: array
      segments_to_delete:
        items:
          type: string
        type: array
      user_id:
        type: integer
    type: object
info:
  contact: {}
  description: Avito homework.
  title: Dynamic user segments server
  version: "1.0"
paths:
  /api/v1/segment:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Segment input
        in: body
        name: slug
        required: true
        schema:
          $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.SegmentInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
      summary: Deletes segment with given slug
    post:
      consumes:
      - application/json
      parameters:
      - description: Segment input
        in: body
        name: slug
        required: true
        schema:
          $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.CreateSegment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
      summary: Creates new segment with given slug
  /api/v1/user/segments:
    get:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.UserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.Segment'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
      summary: Get user's active segments
    post:
      consumes:
      - application/json
      parameters:
      - description: User segments input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.UserSegmentsInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_unbeman_av-prac-task_internal_model.OutputError'
      summary: Updates user's segments
swagger: "2.0"
